### ISSUE TITLE
Disconnects after reading Discord message

### ISSUE THREAD

**Issue by yenfleet** [reactiflux/discord-irc#108]
Trying to link a discord server with an IRC server via ZNC instance. Server it's running on is running Debian Jessie (8.5), and both the ZNC and Discord connections are functional. However, immediately upon receiving a Discord message it throws an error and ceases to function.

Error thrown:

```
BOTNAME@SERVERNAME:~/discord-irc$ npm start -- --config /home/BOTNAME/discord-irc/discord.json

> discord-irc@1.0.1 start /home/BOTNAME/discord-irc
> node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"

26 Aug 22:29:29 - SEND: PRIVMSG #DISCORDCHANNELNAME :<04BOTNAME> Discord -> IRC test.
/home/BOTNAME/discord-irc/node_modules/irc/lib/irc.js:932
    if (!this.conn.requestedDisconnect) {
                  ^
TypeError: Cannot read property 'requestedDisconnect' of null
    at Client.send (/home/BOTNAME/discord-irc/node_modules/irc/lib/irc.js:932:19)
    at dequeue (/home/BOTNAME/discord-irc/node_modules/irc/lib/irc.js:962:22)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "--" "--config" "/home/BOTNAME/discord-irc/discord.json"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! discord-irc@1.0.1 start: `node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-irc@1.0.1 start script 'node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"'.
npm ERR! This is most likely a problem with the discord-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls discord-irc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/BOTNAME/discord-irc/npm-debug.log
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   '/home/BOTNAME/discord-irc/discord.json' ]
2 info using npm@2.15.1
3 info using node@v0.12.15
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart discord-irc@1.0.1
7 info start discord-irc@1.0.1
8 verbose unsafe-perm in lifecycle true
9 info discord-irc@1.0.1 Failed to exec start script
10 verbose stack Error: discord-irc@1.0.1 start: `node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1019:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
11 verbose pkgid discord-irc@1.0.1
12 verbose cwd /home/BOTNAME/discord-irc
13 error Linux 3.16.0-4-amd64
14 error argv "/usr/bin/node" "/usr/bin/npm" "start" "--" "--config" "/home/BOTNAME/discord-irc/discord.json"
15 error node v0.12.15
16 error npm  v2.15.1
17 error code ELIFECYCLE
18 error discord-irc@1.0.1 start: `node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"`
18 error Exit status 1
19 error Failed at the discord-irc@1.0.1 start script 'node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"'.
19 error This is most likely a problem with the discord-irc package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node dist/index.js "--config" "/home/BOTNAME/discord-irc/discord.json"
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs discord-irc
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls discord-irc
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

JSON config:

```
{
        "nickname": "botname",
        "server": "ZNC.server.address",
        "discordToken": "TOKEN",
        "channelMapping": {
                "#discordchannel": "#ircchannel"
        },
        "ircOptions": {
                "userName": "zncuser/server",
                "realName": "something",
                "password": "zncpassword",
                "port": "0000", // custom port (ssl), this comment doesn't exist in the file
                "autoRejoin": "true",
                "autoConnect": "true",
                "secure": "true",
                "selfSigned": "true",
                "certExpired": "true",
                "sasl": "true",
                "floodProtection": "false",
                "floodProtectionDelay": "1000",
                "retryCount": "10",
                "retryDelay": "10000",
                "debug": "true",
                "showErrors": "true"
        }
}
```

**Comment by ekmartin** [comment]
Sorry for the late answer. Does this still persist? Seems like it's an issue with node-irc and its connection to your ZNC server.

**Comment by DarkSpyro003** [comment]
@yenfleet are you still experiencing this issue?
