### ISSUE TITLE
SyntaxError: Unexpected token ... (on ubuntu 16.04)

### ISSUE THREAD

**Issue by SweetShyGirl** [reactiflux/discord-irc#176]
I've ran into a lot of issues on the way

```
user@techs:~/discord-irc$ npm start -- --config config.json

> discord-irc@2.1.6 start /home/user/discord-irc
> node dist/index.js "--config" "config.json"

/home/user/discord-irc/dist/bot.js:95
        this.ircClient.send(...element);
                            ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/discord-irc/dist/helpers.js:12:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.8.6-x86_64-linode78
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--" "--config" "config.json"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! discord-irc@2.1.6 start: `node dist/index.js "--config" "config.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-irc@2.1.6 start script 'node dist/index.js "--config" "config.json"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/index.js "--config" "config.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-irc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/discord-irc/npm-debug.log
```

Debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.1.6~prestart: discord-irc@2.1.6
6 silly lifecycle discord-irc@2.1.6~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.1.6~start: discord-irc@2.1.6
8 verbose lifecycle discord-irc@2.1.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.1.6~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/user/discord-irc/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle discord-irc@2.1.6~start: CWD: /home/user/discord-irc
11 silly lifecycle discord-irc@2.1.6~start: Args: [ '-c', 'node dist/index.js "--config" "config.json"' ]
12 silly lifecycle discord-irc@2.1.6~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.1.6~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.1.6 start: `node dist/index.js "--config" "config.json"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid discord-irc@2.1.6
16 verbose cwd /home/user/discord-irc
17 error Linux 4.8.6-x86_64-linode78
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--" "--config" "config.json"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error discord-irc@2.1.6 start: `node dist/index.js "--config" "config.json"`
22 error Exit status 1
23 error Failed at the discord-irc@2.1.6 start script 'node dist/index.js "--config" "config.json"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js "--config" "config.json"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SweetShyGirl** [comment]
Fixed by removing the ...
Now new error

Traceback:
/home/kyle/discord-irc/dist/bot.js:1
(function (exports, require, module, filename, dirname) { import _ from 'lodash';
                                                              ^^^^^^
```
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kyle/discord-irc/dist/helpers.js:12:12)
    at Module._compile (module.js:410:26)
    at Object.Module.extensions..js (module.js:417:10)
```

code

```
import  from 'lodash';
import irc from 'irc';
```

**Comment by SweetShyGirl** [comment]
Fixed by updating node from v4 to v7
