### ISSUE TITLE
Having issues with starting the bot

### ISSUE THREAD

**Issue by ScrubLord** [reactiflux/discord-irc#189]
I'm new to both github and node.js so if this is the wrong place for this or my problem is super obvious I apologize in advance.

I installed discord-irc by cloning the repository but when I try to do the start command it fails. 

Here is what my config looks like
```js
  {
    "nickname": "stickybot",
    "server": "irc.mlas1.org",
    "discordToken": "MjgwNjQ0ODQ3MjIyNjUyOTI4.C4Madw.IwgCRHzCTnFw0LrAVAZ-etJOefE",
    "channelMapping": {
      "#test2": ""
    }
  },
```
And here is what the debug log looks like
```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.1.7~prestart: discord-irc@2.1.7
6 silly lifecycle discord-irc@2.1.7~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.1.7~start: discord-irc@2.1.7
8 verbose lifecycle discord-irc@2.1.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.1.7~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Tyler\Downloads\discord-irc-master\node_modules\.bin;C:\Users\Tyler\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Users\Tyler\AppData\Local\Microsoft\WindowsApps;C:\Users\Tyler\AppData\Roaming\npm
10 verbose lifecycle discord-irc@2.1.7~start: CWD: C:\Users\Tyler\Downloads\discord-irc-master
11 silly lifecycle discord-irc@2.1.7~start: Args: [ '/d /s /c', 'node dist/index.js' ]
12 silly lifecycle discord-irc@2.1.7~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.1.7~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.1.7 start: `node dist/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-irc@2.1.7
16 verbose cwd C:\Users\Tyler\Downloads\discord-irc-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error discord-irc@2.1.7 start: `node dist/index.js`
22 error Exit status 1
23 error Failed at the discord-irc@2.1.7 start script 'node dist/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks in advance!

**Comment by ekmartin** [comment]
Have you run `npm run build` prior to `npm start -- --config config.json`?

**Comment by ScrubLord** [comment]
I thought I did but maybe not. The results are slightly different now

```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.1.7~prestart: discord-irc@2.1.7
6 silly lifecycle discord-irc@2.1.7~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.1.7~start: discord-irc@2.1.7
8 verbose lifecycle discord-irc@2.1.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.1.7~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Tyler\Downloads\discord-irc-master\node_modules\.bin;C:\Users\Tyler\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Users\Tyler\AppData\Local\Microsoft\WindowsApps;C:\Users\Tyler\AppData\Roaming\npm
10 verbose lifecycle discord-irc@2.1.7~start: CWD: C:\Users\Tyler\Downloads\discord-irc-master
11 silly lifecycle discord-irc@2.1.7~start: Args: [ '/d /s /c', 'node dist/index.js "config.json"' ]
12 silly lifecycle discord-irc@2.1.7~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.1.7~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.1.7 start: `node dist/index.js "config.json"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-irc@2.1.7
16 verbose cwd C:\Users\Tyler\Downloads\discord-irc-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--config" "config.json"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error discord-irc@2.1.7 start: `node dist/index.js "config.json"`
22 error Exit status 1
23 error Failed at the discord-irc@2.1.7 start script 'node dist/index.js "config.json"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js "config.json"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ekmartin** [comment]
When using `npm start` you have to add a double dash before any program arguments, i.e. `npm start -- --config config.json`.

**Comment by ScrubLord** [comment]
Thank you so much for your help so far. I cant believe I forgot to do that. Unfortunately It's still giving me an error.
```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.1.7~prestart: discord-irc@2.1.7
6 silly lifecycle discord-irc@2.1.7~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.1.7~start: discord-irc@2.1.7
8 verbose lifecycle discord-irc@2.1.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.1.7~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Tyler\Downloads\discord-irc-master\node_modules\.bin;C:\Users\Tyler\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Users\Tyler\AppData\Local\Microsoft\WindowsApps;C:\Users\Tyler\AppData\Roaming\npm
10 verbose lifecycle discord-irc@2.1.7~start: CWD: C:\Users\Tyler\Downloads\discord-irc-master
11 silly lifecycle discord-irc@2.1.7~start: Args: [ '/d /s /c', 'node dist/index.js "--config" "config.json"' ]
12 silly lifecycle discord-irc@2.1.7~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.1.7~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.1.7 start: `node dist/index.js "--config" "config.json"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-irc@2.1.7
16 verbose cwd C:\Users\Tyler\Downloads\discord-irc-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--config" "config.json"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error discord-irc@2.1.7 start: `node dist/index.js "--config" "config.json"`
22 error Exit status 1
23 error Failed at the discord-irc@2.1.7 start script 'node dist/index.js "--config" "config.json"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js "--config" "config.json"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ekmartin** [comment]
Not sure why your npm error message is so verbose, can't really see the actual error.
Try running the start script directly, `node dist/index.js --config config.json`. Also, in your original configuration you haven't listed a name for both sides of the channel mapping - have you done so now?

**Comment by ScrubLord** [comment]
I changed it now so both sides say "#test2"

after trying to run the start script directly, I recive this error

```txt
ConfigurationError: The configuration file contains invalid JSON
    at ConfigurationError (C:\Users\Tyler\Downloads\discord-irc-master\dist\errors.js:8:5)
    at readJSONConfig (C:\Users\Tyler\Downloads\discord-irc-master\dist\cli.js:48:13)
    at Object.run [as default] (C:\Users\Tyler\Downloads\discord-irc-master\dist\cli.js:62:98)
    at Object.<anonymous> (C:\Users\Tyler\Downloads\discord-irc-master\dist\index.js:23:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by ekmartin** [comment]
It's probably your trailing comma at the end. You can use http://jsonlint.com/ to see what went wrong. By the way, you should probably create a new token if the one you linked here was real. Also, if both sides of the channel mapping is named #test2, that means that both your IRC and Discord channels have that name.

**Comment by ekmartin** [comment]
Gonna close this, feel free to PM me on Discord if you need more help: ekmartin#5764.
