### ISSUE TITLE
Problem starting.

### ISSUE THREAD

**Issue by MattiSony** [reactiflux/discord-irc#24]
Hey, I'm not able to start discord-irc.
When I do `npm start -- --config config.json` I get this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart discord-irc@0.4.2
6 info start discord-irc@0.4.2
7 verbose unsafe-perm in lifecycle true
8 info discord-irc@0.4.2 Failed to exec start script
9 verbose stack Error: discord-irc@0.4.2 start: `node dist/index.js "config.json"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid discord-irc@0.4.2
11 verbose cwd C:\Users\MattiSony\node_modules\discord-irc
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--config" "config.json"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error discord-irc@0.4.2 start: `node dist/index.js "config.json"`
17 error Exit status 1
18 error Failed at the discord-irc@0.4.2 start script 'node dist/index.js "config.json"'.
18 error This is most likely a problem with the discord-irc package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node dist/index.js "config.json"
18 error You can get their info via:
18 error     npm owner ls discord-irc
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by ekmartin** [comment]
Weird. Could you paste the output from running `node dist/index.js --config config.json` (run `npm install && npm run build` first if you haven't).

**Comment by MattiSony** [comment]
```C:\Users\MattiSony\node_modules\discord-irc>node dist/index.js --config config.j
son

C:\Users\MattiSony\node_modules\discord-irc\dist\cli.js:46
      throw new _errors.ConfigurationError('The configuration file contains inva
lid JSON');
      ^
 ConfigurationError: The configuration file contains invalid JSON
```

my config file: 
```
[
  {
    "nickname": "Username",
    "server": "irc.server.com",
    "discordEmail": "user@mail.com",
    "discordPassword": "Password123",
    "channelMapping": {
      "#discord": "#matti"
    }
  },

]
```

**Comment by ekmartin** [comment]
You have a trailing after your configuration object, which isn't allowed in JSON.

**Comment by ekmartin** [comment]
I.e. the correct configuration would be:

```json
  {
    "nickname": "Username",
    "server": "irc.server.com",
    "discordEmail": "user@mail.com",
    "discordPassword": "Password123",
    "channelMapping": {
      "#discord": "#matti"
    }
  }
```

You don't need the array brackets when you only have one bot, but it doesn't make a difference if you have them there either.

**Comment by MattiSony** [comment]
Got it working, thanks :)

**Comment by ekmartin** [comment]
Glad to hear!
