### ISSUE TITLE
Can't start discord-irc

### ISSUE THREAD

**Issue by Ratismal** [reactiflux/discord-irc#26]
Whenever I attempt to run discord-irc, it immediately crashes.

```
me@my-computer:~$ discord-irc --config /path/to/config.json

/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/lib/Voice/StreamIntent.js:9
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/lib/Voice/StreamIntent.js:9:113)
    at /usr/local/lib/node_modules/discord-irc/node_modules/discord.js/lib/Voice/StreamIntent.js:16:2
    at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/lib/Voice/StreamIntent.js:25:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/lib/Voice/VoiceConnection.js:38:21)
```
For future reference, I replaced my config path to /path/to/config.json for ticket purposes. I'm running Ubuntu 14.04.3 LTS. Help would be appreciated.

**Comment by lrabe** [comment]
What's your output of node -v?
Ubuntu 14.04 LTS repos only have node 0.10 while 0.12 is required.

**Comment by Ratismal** [comment]
Updated node, and it works perfectly. Thanks!

**Comment by ekmartin** [comment]
Thanks @Irabe.
