### ISSUE TITLE
Bot not starting on heroku

### ISSUE THREAD

**Issue by Bluscream** [reactiflux/discord-irc#276]
```
2017-07-22T22:14:48.344341+00:00 heroku[web.1]: Starting process with command `npm start`

2017-07-22T22:14:50.259561+00:00 app[web.1]: 

2017-07-22T22:14:50.259574+00:00 app[web.1]: > discord-irc@2.4.1 start /app

2017-07-22T22:14:50.259574+00:00 app[web.1]: > node dist/index.js

2017-07-22T22:14:50.259575+00:00 app[web.1]: 

2017-07-22T22:14:50.729931+00:00 heroku[web.1]: Process exited with status 1

2017-07-22T22:14:50.741219+00:00 heroku[web.1]: State changed from starting to crashed

2017-07-22T22:14:50.651384+00:00 app[web.1]: module.js:487

2017-07-22T22:14:50.651399+00:00 app[web.1]:     throw err;

2017-07-22T22:14:50.651402+00:00 app[web.1]:     ^

2017-07-22T22:14:50.651403+00:00 app[web.1]: 

2017-07-22T22:14:50.651404+00:00 app[web.1]: Error: Cannot find module '/app/dist/index.js'

2017-07-22T22:14:50.651405+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:485:15)

2017-07-22T22:14:50.651406+00:00 app[web.1]:     at Function.Module._load (module.js:437:25)

2017-07-22T22:14:50.651406+00:00 app[web.1]:     at Function.Module.runMain (module.js:605:10)

2017-07-22T22:14:50.651407+00:00 app[web.1]:     at startup (bootstrap_node.js:158:16)

2017-07-22T22:14:50.651408+00:00 app[web.1]:     at bootstrap_node.js:575:3

2017-07-22T22:14:50.662646+00:00 app[web.1]: npm ERR! code ELIFECYCLE

2017-07-22T22:14:50.662800+00:00 app[web.1]: npm ERR! errno 1

2017-07-22T22:14:50.662905+00:00 app[web.1]: npm ERR! discord-irc@2.4.1 start: `node dist/index.js`

2017-07-22T22:14:50.663008+00:00 app[web.1]: npm ERR! Exit status 1

2017-07-22T22:14:50.663142+00:00 app[web.1]: npm ERR! 

2017-07-22T22:14:50.663285+00:00 app[web.1]: npm ERR! Failed at the discord-irc@2.4.1 start script.

2017-07-22T22:14:50.663411+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

2017-07-22T22:14:50.664352+00:00 app[web.1]: 

2017-07-22T22:14:50.664512+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:

2017-07-22T22:14:50.664607+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-07-22T22_14_50_658Z-debug.log
```

**Comment by Throne3d** [comment]
How did you go about installing the app? It looks like you might have cloned the source and forgotten to run `npm run build`.

**Comment by oscar-beltran** [comment]
Well, actually I had the same problem, I solved it the next way:
1. Locally I cloned and installed the repository, like the readme.md file says.
2. Then I created the **Procfile** file with the line:
`worker: npm start -- --config ./config.json`
3. Finally, I have edited .**gitignore** file for allow push the **dist/** folder to the heroku repo, also do not forget allow your **config.json** file.

Sorry for my bad English.

**Comment by Bluscream** [comment]
Thanks !

**Comment by ekmartin** [comment]
Note that Heroku restarts dynos once every now and then (might be possible to work around with worker dynos) - so not really optimal for a chat bot (which needs 24/7 uptime).
