### ISSUE TITLE
Cannot find module 'discord.js'

### ISSUE THREAD

**Issue by Deph0** [reactiflux/discord-irc#3]
```javascript
$ node index.js --config config.json 
module.js:339
    throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/discordapp/node_modules/discord-irc/lib/bot.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by Deph0** [comment]
nvm, node-gyp failed to rebuild on install.

**Comment by Deph0** [comment]
actually, this still happens, sorry- jumped the gun.

**Comment by ekmartin** [comment]
This should be fixed with https://github.com/reactiflux/discord-irc/commit/798395f4f47a8112a221f4ca31cb487ffaced146 (I had managed to put discord.irc as a devDependency). I've published a new version, 0.1.1, should work now.

**Comment by Deph0** [comment]
another issue accrued:

````
module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/git/discord-irc/lib/helpers.js:1:71)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

**Comment by ekmartin** [comment]
Are you sure it was installed properly? https://github.com/reactiflux/discord-irc/blob/master/package.json#L37

**Comment by Deph0** [comment]
this happend when i rm'd the node_modules and redid npm install:

```javascript
$ node
> var discordIRC = require('discord-irc');
undefined
> var config = require('./config.json');
undefined
> discordIRC(config);
ReferenceError: Promise is not defined
    at Client.login (/home/ankr/node/node_modules/discord-irc/node_modules/discord.js/lib/Client.js:132:15)
    at Bot.connect (/home/ankr/node/node_modules/discord-irc/lib/bot.js:48:16)
    at exports.createBots (/home/ankr/node/node_modules/discord-irc/lib/helpers.js:21:9)
    at repl:1:12
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
 
```

**Comment by ekmartin** [comment]
Hm, that's an issue in discord.js. What node version are you using?

**Comment by Deph0** [comment]
```javascript
$ node -v
v0.10.25
$ npm -v
1.3.10
```
should be latest, as i got it off the nodejs webpage (binaries)

**Comment by ekmartin** [comment]
0.10.25 is quite old (January 2014). The last version is 4.2.1, but I've got it to work using 0.12.2 too. You can download the latest version of Node here: https://nodejs.org/dist/v4.2.1/. I recommend using [nvm](https://github.com/creationix/nvm) though, which will let you easily install and use different versions.

**Comment by Deph0** [comment]
well that doesn't make a whole lot of sense, https://nodejs.org/en/download/ points to v4.2.1, which is what I downloaded!

**Comment by ekmartin** [comment]
No problem at all - glad you got it working.
