### ISSUE TITLE
SSL network

### ISSUE THREAD

**Issue by scramble0** [reactiflux/discord-irc#308]
Trying to connect to `hub.wirelesspt.net SSL 6697`
So it requires on "ircOptions":  `      "port": 6697,
      "secure": true,
      "selfSigned": true,
      "certExpired": true `

But I get the following error on console

> info: Connected to IRC
/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^
TypeError: Cannot read property 'add' of undefined
    at Client.ircClient.on (/usr/lib/node_modules/discord-irc/dist/bot.js:157:61)
    at emitThree (events.js:135:13)
    at Client.emit (events.js:216:7)
    at Client.<anonymous> (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:495:22)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at iterator (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.handleData (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:115:13)

on IRC

`botname (bot@address) has quit IRC (Read error)`

help? thank you!

**Comment by Throne3d** [comment]
Uh, just to check, are you on an old version? It looks like that's using the `irc` library (instead of `irc-upd`, the newer one).

**Comment by scramble0** [comment]
Toying arround  and deployed a new instance for this network, didn't check for updates! that fixed it.
Thanks for the awesome super reply @Throne3d

**Comment by Throne3d** [comment]
No problem! If it happens again, it could be an actual problem – the code around there has been a little intermittent – but hopefully it won't.
