### ISSUE TITLE
Question (and npm ERR!)

### ISSUE THREAD

**Issue by SalatielSauer** [reactiflux/discord-irc#309]
i'm getting some errors on the node prompt...
```
C:\Users\Salatiel\Documents\discordbot\discord-irc-master>npm start -- --config
/path/to/config.json

> discord-irc@2.4.2 start C:\Users\Salatiel\Documents\discordbot\discord-irc-mas
ter
> node dist/index.js "--config" "/path/to/config.json"

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\path\to\config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at readJSONConfig (C:\Users\Salatiel\Documents\discordbot\discord-irc-master
\dist\cli.js:43:35)
    at Object.run [as default] (C:\Users\Salatiel\Documents\discordbot\discord-i
rc-master\dist\cli.js:62:98)
    at Object.<anonymous> (C:\Users\Salatiel\Documents\discordbot\discord-irc-ma
ster\dist\index.js:23:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--config" "/path/to/config.jso
n"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! discord-irc@2.4.2 start: `node dist/index.js "--config" "/path/to/confi
g.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-irc@2.4.2 start script 'node dist/index.js "--con
fig" "/path/to/config.json"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/index.js "--config" "/path/to/config.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-irc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Salatiel\Documents\discordbot\discord-irc-master\npm-debug
.log

C:\Users\Salatiel\Documents\discordbot\discord-irc-master>
```

Here is the Debug file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'config.json' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.4.2~prestart: discord-irc@2.4.2
6 silly lifecycle discord-irc@2.4.2~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.4.2~start: discord-irc@2.4.2
8 verbose lifecycle discord-irc@2.4.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.4.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Salatiel\Documents\discordbot\discord-irc-master\node_modules\.bin;C:\Users\Salatiel\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files\AMD APP\bin\x86;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Windows Live\Shared;C:\Program Files\Trend Micro\AMSP;C:\Program Files\GtkSharp\2.12\bin;C:\Program Files\ImageConverter Plus;C:\Program Files\Jahshaka\..\gtk2\bin;C:\Program Files\Jahshaka\..\mlt\bin;C:\Program Files\OpenLibraries\bin;C:\TDM-GCC-32\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Salatiel\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Salatiel\AppData\Local\Programs\Python\Python35-32\;C:\Users\Salatiel\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Salatiel\AppData\Local\Programs\Python\Python36-32\;C:\Users\Salatiel\AppData\Roaming\npm
10 verbose lifecycle discord-irc@2.4.2~start: CWD: C:\Users\Salatiel\Documents\discordbot\discord-irc-master
11 silly lifecycle discord-irc@2.4.2~start: Args: [ '/d /s /c', 'node dist/index.js "config.json"' ]
12 silly lifecycle discord-irc@2.4.2~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.4.2~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.4.2 start: `node dist/index.js "config.json"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-irc@2.4.2
16 verbose cwd C:\Users\Salatiel\Documents\discordbot\discord-irc-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "config.json"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error discord-irc@2.4.2 start: `node dist/index.js "config.json"`
22 error Exit status 1
23 error Failed at the discord-irc@2.4.2 start script 'node dist/index.js "config.json"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js "config.json"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
I'm doing something wrong... but what? :p, if you need more info, please tell me.

**Comment by Throne3d** [comment]
You should be creating a config file (examples given in the README) and replacing `/path/to/config.json` with the location of that config. Currently you're pointing it at `/path/to/config.json` for the config file (as in, `C:\path\to\config.json` on Windows), which doesn't exist.

**Comment by SalatielSauer** [comment]
@Throne3d Thanks! this is fixed now.

**Comment by Throne3d** [comment]
@SalatielSauer It's in `.md` format because that allows us to add formatting? It's "Markdown" and displays properly on GitHub if you look here: https://github.com/reactiflux/discord-irc/blob/master/README.md
