### ISSUE TITLE
markdown in irc nickname

### ISSUE THREAD

**Issue by Helianthella** [reactiflux/discord-irc#327]
If a user on IRC is named `_nick_` it will be sent to discord as-is and so appear as `nick` but italicized instead of appearing as `_nick_` non-italicized. To avoid this, discord-irc should prepend any markdown in nicknames with backslashes so `_nick_` would be sent as `\_nick\_` and show properly on discord

**Comment by unnes** [comment]
I'm trying to block an IRC user with the name "|N_X|4_cG_4iH4xW\Nkx1z2GXL0u"

Trying to escape the underscores and backslashes results in the following error:

`/usr/lib/node_modules/discord-irc/dist/cli.js:48
      throw new _errors.ConfigurationError('The configuration file contains invalid JSON');
      ^

ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (/usr/lib/node_modules/discord-irc/dist/cli.js:48:13)
    at Object.run [as default] (/usr/lib/node_modules/discord-irc/dist/cli.js:62:98)
    at Object.<anonymous> (/usr/lib/node_modules/discord-irc/dist/index.js:23:27)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
`

Any suggestions?

**Comment by mekolat** [comment]
@unnes try *HTML entities*

**Comment by Throne3d** [comment]
You shouldn't need to escape underscores, just backslashes and quotes. If you're getting an "invalid JSON" error, you may have done it wrong (perhaps JSON doesn't like you escaping underscores). This also seems mostly unrelated to the main issue here, so I'd suggest putting this into a new issue if you still have trouble.

@mekolat I don't think that helps solve the problem? How would you wrap a bit of JSON in an inline code block, and why would HTML entities be relevant – it's JSON?

**Comment by mekolat** [comment]
I meant on Discord, not in the `config.json` file; I thought @unnes was trying to escape the name on Discord, which is what the issue (#237) is about..

**Comment by Throne3d** [comment]
Ah, right – no, I think it's an unrelated issue which was put here erroneously.
