### ISSUE TITLE
Crashing on http:// in irc channel

### ISSUE THREAD

**Issue by keenerb** [reactiflux/discord-irc#34]
Whenever someone links to an http site in discord, the bot crashes.

`/usr/lib/node_modules/discord-irc/node_modules/discord.js/lib/Util/Cache.js:1
],old[this[discrimS]]);if(item){var index=this.indexOf(item);Object.assign(thi
                                                                    ^
TypeError: undefined is not a function
    at Cache.update (/usr/lib/node_modules/discord-irc/node_modules/discord.js/lib/Util/Cache.js:1:2168)
    at WebSocket.websocket.onmessage (/usr/lib/node_modules/discord-irc/node_modules/discord.js/lib/Client/InternalClient.js:64:439)
    at WebSocket.onMessage (/usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:816:10)
    at /usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/Receiver.js:364:5)
    at /usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (/usr/lib/node_modules/discord-irc/node_modules/discord.js/node_modules/ws/lib/Receiver.js:482:12`

**Comment by AdrianLove** [comment]
I'm getting the same behavior, were you able to find a workaround?

**Comment by ekmartin** [comment]
I'm not able to reproduce this after upgrading to discord.js version 6.1.0. I've released a new version of discord-irc with the upgrades, as version 0.6.1. Would be nice if you tested it!

**Comment by AdrianLove** [comment]
Updated, works great. Thanks for the fix @ekmartin <3
