### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TechGamer21** [reactiflux/discord-irc#358]
SyntaxError: C:\Users\agt20\Discord-SelfBot\config\config.json: Unexpected token M in JSON at position 16
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\agt20\Discord-SelfBot\self.js:15:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

Sorry if the way I put it sounds a bit mean since I haven't explained it in a better way, sorry about that

**Comment by ekmartin** [comment]
Did you figure it out? The error means you have a syntax error in your configuration file. If you remove the inline comments you can run it through something like https://jsonlint.com/ to see what's wrong.

**Comment by TechGamer21** [comment]
I've fixed it, I had 2 quotation marks in the User token, I also posted this on the wrong self bot xd, thanks for replying though
