### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by TheToPPazZe** [reactiflux/discord-irc#381]
Hi !
I start to create a bot 1hours ago
A the start, my bot work with no problem
But now, it say that i have an error

C:\Users\HP 8000v2\Documents\DiscordBot>node .\index.js
C:\Users\HP 8000v2\Documents\DiscordBot\index.js:19
import { GuildMember, Guild } from 'discord.js';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
Someone can help me ?

(Sorry if my english is bad, i'm French ^^)

**Comment by Throne3d** [comment]
This looks like it's related to discord.js, not discord-irc. That is, <https://github.com/discordjs/discord.js>, not this project?

**Comment by ekmartin** [comment]
Yeah, seems like you're using discord.js - not discord-**irc** :)
