### ISSUE TITLE
problems finding ICU

### ISSUE THREAD

**Issue by kieeps** [reactiflux/discord-irc#390]
I seem to have a problem finding ucsdet.h with npm.
I'm on freebsd and i'w made sure to have icu installed, but i dont understad where npm is looking for it...

```
locate ucsdet.h
/root/icu/source/i18n/unicode/ucsdet.h
/usr/local/include/unicode/ucsdet.h
```

as shown above thats where the files are on my system.

```
> node-icu-charset-detector@0.2.0 install /root/discord-irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

gmake: Entering directory '/root/discord-irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:10: fatal error: 'unicode/ucsdet.h' file not found
#include <unicode/ucsdet.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [node-icu-charset-detector.target.mk:93: Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
gmake: Leaving directory '/root/discord-irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System FreeBSD 11.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/discord-irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN lifecycle discord-irc@2.6.0~prepare: cannot run in wd discord-irc@2.6.0 npm run build (wd=/root/discord-irc)
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-icu-charset-detector@0.2.0 (node_modules/node-icu-charset-detector):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-icu-charset-detector@0.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 4.99s
```

**Comment by ekmartin** [comment]
Just released a version of discord-irc that doesn't need `icu` (thanks to the changes @Throne3d has made to node-irc). Give it a try?

**Comment by kieeps** [comment]
just a FYI, it worked great now ;)
