### ISSUE TITLE
Bot Disconnecting When Writing Message

### ISSUE THREAD

**Issue by marcosbucarte** [reactiflux/discord-irc#395]
My bot that was working perfectly until yesterday is occurring error when entering message in the irc or in the discord and the connection with it falls, below the error displayed.

Any solution for this?

```
(node:2122) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/usr/lib/node_modules/discord-irc/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:2122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Throne3d** [comment]
Are you sure the bot isn't missing permissions in the server it's trying to access? (Like the error says)

**Comment by marcosbucarte** [comment]
I found the problem was from discord.
