### ISSUE TITLE
ConfigurationError: The configuration file contains invalid JSON

### ISSUE THREAD

**Issue by vzrenggamani** [reactiflux/discord-irc#396]
Just started to play with this but no luck
```
root@cs-6000-devshell-vm-b9847605-399e-4461-9d1c-96a84a1dd31d:/home/rengga_prakoso/discord-irc/discord-irc# npm start -- --config ./config.json
> discord-irc@2.6.0 start /home/rengga_prakoso/discord-irc/discord-irc
> node dist/index.js "--config" "./config.json"
/home/rengga_prakoso/discord-irc/discord-irc/dist/cli.js:48
      throw new _errors.ConfigurationError('The configuration file contains invalid JSON');
      ^
ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (/home/rengga_prakoso/discord-irc/discord-irc/dist/cli.js:48:13)
    at Object.run [as default] (/home/rengga_prakoso/discord-irc/discord-irc/dist/cli.js:62:98)
    at Object.<anonymous> (/home/rengga_prakoso/discord-irc/discord-irc/dist/index.js:23:27)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-irc@2.6.0 start: `node dist/index.js "--config" "./config.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-irc@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-04T10_51_32_998Z-debug.log
```

**Comment by Throne3d** [comment]
So, first of all, you probably want to change your discord token because that looks recoverable from the image (and then someone can control your bot).

Second of all: why do you have a trailing comma on the object? And why is this not inside an array? The [example configuration](https://github.com/reactiflux/discord-irc#example-configuration) shows it inside square brackets (i.e. inside an array), and only has a comma because there's a second bot. I'd remove the comma, and then wrap it in square brackets, and then see if it works.

**Comment by vzrenggamani** [comment]
```
[  
   {  
      "nickname":"AuruChan",
      "server":"chat.scoutlink.net",
      "discordToken":"BLABBLA",
      "channelMapping":{  
         "#441898947787620362":"#indonesian"
      }
   }
]
```
Like that ? sorry, i dont understand well
