### ISSUE TITLE
SyntaxError: Unexpected token ) (Can someone Help me please)

### ISSUE THREAD

**Issue by Verzu** [reactiflux/discord-irc#413]
From what i know the code should be right but im getting this erroor message when i try turning the bot on.
This is the error message: 
SyntaxError: Unexpected token )
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)

This is The code: 
https://gyazo.com/0471d6e3c5755a30e120c1dc271d1c43

**Comment by Throne3d** [comment]
We're not discord.js! You want to look here instead: <https://github.com/discordjs/discord.js>
