### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by adrianmihalko** [reactiflux/discord-irc#446]
Do you see any valuble info in this log?

```
2018-11-08T16:43:13.592Z error: Received error event from Discord {"target":{"domain":null,"_events":{},"_eventsCount":4,"readyState":2,"protocol":"","_binaryType":"nodebuffer","_closeFrameReceived":false,"_closeFrameSent":false,"_closeMessage":"","_closeTimer":null,"_finalized":true,"_closeCode":1006,"_extensions":{},"_isServer":false,"_receiver":null,"_sender":null,"_socket":null,"_error":null,"url":"wss://gateway.discord.gg/?v=6&encoding=json","_req":null},"type":"error","error":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"timestamp":"2018-11-08T16:43:13.592Z"}
2018-11-08T16:43:19.768Z error: Received error event from Discord {"target":{"domain":null,"_events":{},"_eventsCount":4,"readyState":2,"protocol":"","_binaryType":"nodebuffer","_closeFrameReceived":false,"_closeFrameSent":false,"_closeMessage":"","_closeTimer":null,"_finalized":true,"_closeCode":1006,"_extensions":{},"_isServer":false,"_receiver":null,"_sender":null,"_socket":null,"_error":null,"url":"wss://gateway.discord.gg/?v=6&encoding=json","_req":null},"type":"error","error":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"timestamp":"2018-11-08T16:43:19.768Z"}
2018-11-08T16:43:25.574Z error: Received error event from Discord {"target":{"domain":null,"_events":{},"_eventsCount":4,"readyState":2,"protocol":"","_binaryType":"nodebuffer","_closeFrameReceived":false,"_closeFrameSent":false,"_closeMessage":"","_closeTimer":null,"_finalized":true,"_closeCode":1006,"_extensions":{},"_isServer":false,"_receiver":null,"_sender":null,"_socket":null,"_error":null,"url":"wss://gateway.discord.gg/?v=6&encoding=json","_req":null},"type":"error","error":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"timestamp":"2018-11-08T16:43:25.574Z"}
2018-11-08T16:43:33.423Z info: Connected to Discord {"timestamp":"2018-11-08T16:43:33.423Z"}
/usr/lib/node_modules/discord-irc/node_modules/winston/lib/winston/logger.js:237
      throw ex;
      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Printf.formatter [as template] (/usr/lib/node_modules/discord-irc/dist/logger.js:14:32)
    at Printf.transform (/usr/lib/node_modules/discord-irc/node_modules/logform/printf.js:11:26)
    at Format.info [as transform] (/usr/lib/node_modules/discord-irc/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/usr/lib/node_modules/discord-irc/node_modules/winston/lib/winston/logger.js:235:29)
    at DerivedLogger.Transform._read (/usr/lib/node_modules/discord-irc/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/usr/lib/node_modules/discord-irc/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/lib/node_modules/discord-irc/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/discord-irc/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DerivedLogger.Writable.write (/usr/lib/node_modules/discord-irc/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

Today it just crashed for some reason.

**Comment by imnotjames** [comment]
Similar here.

```
(node:8288) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Printf.formatter [as template] (/home/media/discord-irc/discord-irc/dist/logger.js:14:32)
    at Printf.transform (/home/media/discord-irc/discord-irc/node_modules/logform/printf.js:11:26)
    at Format.info [as transform] (/home/media/discord-irc/discord-irc/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/home/media/discord-irc/discord-irc/node_modules/winston/lib/winston/logger.js:235:29)
    at DerivedLogger.Transform._read (/home/media/discord-irc/discord-irc/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/home/media/discord-irc/discord-irc/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/media/discord-irc/discord-irc/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/media/discord-irc/discord-irc/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DerivedLogger.Writable.write (/home/media/discord-irc/discord-irc/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:334:11)
(node:8288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8288) UnhandledPromiseRejectionWarning: TypeError: this.client.listenerCount is not a function
    at item.request.gen.end (/home/media/discord-irc/discord-irc/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:87:29)
    at then (/home/media/discord-irc/discord-irc/node_modules/snekfetch/src/index.js:214:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

I'm taking a look at this today to figure out if there's something simple we can do differently to handle this..
