### ISSUE TITLE
Can't send from IRC to Discord afterwards.

### ISSUE THREAD

**Issue by DaVinci030** [reactiflux/discord-irc#461]
I've been using this for more than a year. I'm not good at explaining but here's the issue I copied from the command prompt.

> (node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) UnhandledPromiseRejectionWarning: TypeError: this.client.listenerCou
nt is not a function
    at item.request.gen.end (C:\Users\TV-Nihon\AppData\Roaming\npm\node_modules\
discord-irc\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.j
s:87:29)
    at then (C:\Users\TV-Nihon\AppData\Roaming\npm\node_modules\discord-irc\node
_modules\snekfetch\src\index.js:214:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:5220) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead
(node:5220) DeprecationWarning: Collection#find: pass a function instead<

After the "UnhandledPromiseRejectionWarning" shows up, it cannot send transmission from IRC to Discord from one of the multiple channels (while the rest are working).

Screenshots from Discord: https://i.imgur.com/9N6TX6e.png, IRC: https://i.imgur.com/jfaaVTv.png

Can you fix that issue?

P.S. "DeprecationWarning: Collection#find: pass a function instead" annoys me so can you do something about that?

**Comment by stonerl** [comment]
I do have the exact same problem. Do you need any more debug logging?

**Comment by Throne3d** [comment]
This looks like it's coming from within discord.js, an upstream library used by discord-irc. I have no idea what it's trying to do there, though, and the bot uses the latest version.

**Comment by stonerl** [comment]
Thanks for looking into it, let's wait for upstream to fix it. As a workaround, I use a systemd timer to restart discord-irc every hour.

**Comment by Kovaelin** [comment]
Seems similar to #326 and #328.

**Comment by zertap** [comment]
The error message occurs for me when many lines are sent at once. IRC-> discord cuts off on 5th or so message, iirc.

**Comment by Throne3d** [comment]
I'll close this issue for now, as I haven't heard anything recent and the above logs look strange (our uses of `find` are all currently valid?). If you notice any recent connectivity issues, please get back in touch!

**Comment by ticpu** [comment]
Sorry to say, but I'm still getting that and will probably add --unhandled-rejections=strict to the service to see if systemd can just restart it instead of being blind about the bot not working.
```
Aug 12 18:49:13 masterpi npm[2731]: (node:2731) UnhandledPromiseRejectionWarning: FetchError: request to https://discordapp.com/api/v7/channels/653307272004632623/messages failed, reason: getaddrinfo EAI_AGAIN discordapp.com
Aug 12 18:49:13 masterpi npm[2731]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
Aug 12 18:49:13 masterpi npm[2731]:     at runMicrotasks (<anonymous>)
Aug 12 18:49:13 masterpi npm[2731]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Aug 12 18:49:13 masterpi npm[2731]: (node:2731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 32415)
```

**Comment by Throne3d** [comment]
Hrrm, that's a shame. Are you testing out the latest alpha version ([v2.9.0-alpha](https://github.com/reactiflux/discord-irc/releases/tag/v2.9.0-alpha))? If not, would you be able to try that out and see if the same issue occurs? This seems to be happening in discord.js, which is a library we rely on, but it's had quite a significant recent update, and I wonder if it might have improved the behavior around this.

**Comment by ticpu** [comment]
It is running v2.8.1-11-g5af02c1 at the moment, is it considered 2.9 or should I git pull?

**Comment by Throne3d** [comment]
I can't actually seem to find g5af02c1 in the repo (is that a Git commit?), so I'm not sure if you're on a more recent version than the release, but 2.8.1 was 41f8444d17b2b282c437b5f871f0252968c03525, and the main relevant change for 2.9.0-alpha happened in f047ce0224d0bf5bb769659c8015ed7371879d94 - at the end of the [v2.8.1...v2.9.0-alpha](https://github.com/reactiflux/discord-irc/compare/v2.8.1...v2.9.0-alpha) comparison.

**Comment by ticpu** [comment]
My bad, I should have git log before posting.  g5af02c1 = git shorthash when you remove the leading g.  Git log shows that this short hash is "Add 2.9.0-alpha to CHANGELOG" 5af02c16c60ba53586a733237face76eed017da0

**Comment by ticpu** [comment]
I almost forgot about this ticket and when I checked again, surprise!  The service crashed a couple time but systemd restarted it as expected.

With strict mode enabled, here is the log that is spit out before crashing:

```
Sep 10 12:57:43 masterpi node[27874]: 2020-09-10T16:57:43.620Z info: Connected to Discord
Sep 10 12:57:44 masterpi node[27874]: 2020-09-10T16:57:44.669Z info: Connected to IRC
Sep 10 12:57:44 masterpi node[27874]: 2020-09-10T16:57:44.737Z info: Connected to IRC
Sep 10 12:57:53 masterpi node[27874]: 2020-09-10T16:57:53.724Z info: Connected to Discord
Sep 14 17:17:46 masterpi node[27874]: 2020-09-14T21:17:46.664Z error: Received error event from IRC {
Sep 14 17:17:46 masterpi node[27874]:   prefix: 'wolfe.freenode.net',
Sep 14 17:17:46 masterpi node[27874]:   server: 'wolfe.freenode.net',
Sep 14 17:17:46 masterpi node[27874]:   command: 'err_notregistered',
Sep 14 17:17:46 masterpi node[27874]:   rawCommand: '451',
Sep 14 17:17:46 masterpi node[27874]:   commandType: 'error',
Sep 14 17:17:46 masterpi node[27874]:   args: [ '*', 'You have not registered' ]
Sep 14 17:17:46 masterpi node[27874]: }
Sep 14 17:17:49 masterpi node[27874]: 2020-09-14T21:17:49.855Z info: Connected to IRC
Sep 14 17:17:57 masterpi node[27874]: 2020-09-14T21:17:57.987Z info: Connected to IRC
Sep 14 17:24:42 masterpi node[27874]: 2020-09-14T21:24:42.989Z info: Connected to IRC
Sep 14 20:20:46 masterpi node[27874]: 2020-09-15T00:20:46.050Z error: Received error event from IRC {
Sep 14 20:20:46 masterpi node[27874]:   prefix: 'card.freenode.net',
Sep 14 20:20:46 masterpi node[27874]:   server: 'card.freenode.net',
Sep 14 20:20:46 masterpi node[27874]:   command: 'err_cannotsendtochan',
Sep 14 20:20:46 masterpi node[27874]:   rawCommand: '404',
Sep 14 20:20:46 masterpi node[27874]:   commandType: 'error',
Sep 14 20:20:46 masterpi node[27874]:   args: [ 'TiCPU_', '#btrfs', 'Cannot send to nick/channel' ]
Sep 14 20:20:46 masterpi node[27874]: }
Sep 14 20:32:35 masterpi node[27874]: /app/node_modules/discord.js/src/rest/RequestHandler.js:158
Sep 14 20:32:35 masterpi node[27874]:           new HTTPError(res.statusText, res.constructor.name, res.status, item.request.method, request.path),
Sep 14 20:32:35 masterpi node[27874]:           ^
Sep 14 20:32:35 masterpi node[27874]: Response: Internal Server Error
Sep 14 20:32:35 masterpi node[27874]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:158:11)
Sep 14 20:32:35 masterpi node[27874]:     at runMicrotasks (<anonymous>)
Sep 14 20:32:35 masterpi node[27874]:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
Sep 14 20:32:35 masterpi node[27874]:   code: 500,
Sep 14 20:32:35 masterpi node[27874]:   method: 'post',
Sep 14 20:32:35 masterpi node[27874]:   path: '/channels/653307177762553881/messages'
Sep 14 20:32:35 masterpi node[27874]: }
Sep 14 20:32:35 masterpi systemd[1]: discord-irc.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 20:32:35 masterpi systemd[1]: discord-irc.service: Failed with result 'exit-code'.
Sep 14 20:32:35 masterpi systemd[1]: discord-irc.service: Consumed 4min 43.594s CPU time.
Sep 14 20:32:45 masterpi systemd[1]: discord-irc.service: Scheduled restart job, restart counter is at 1.
Sep 14 20:32:45 masterpi systemd[1]: Stopped Discord to IRC bridge.
Sep 14 20:32:45 masterpi systemd[1]: discord-irc.service: Consumed 4min 43.594s CPU time.
Sep 14 20:32:45 masterpi systemd[1]: Started Discord to IRC bridge.
```

**Comment by Throne3d** [comment]
Based on that log, it looks like something went wrong internally in Discord, since it returned an Internal Server Error?

The upstream `discord.js` [provides a `retryLimit` option for 500-error requests](https://discord.js.org/#/docs/main/stable/typedef/ClientOptions), which looks targeted at this. I'll try adding a retry limit of 3 (rather than the default of 1), and then cut a beta, to see if that helps out!

**Comment by ticpu** [comment]
From my point of view, this issue is fixed, when the retries can't handle it, the only way to fix 500 errors is wait for the platform to heal itself and restart.  So, having the service manager handle the restart does it for me.
