### ISSUE TITLE
Can't install (NPM)

### ISSUE THREAD

**Issue by TLWXPUser** [reactiflux/discord-irc#519]
TypeError: Cannot read property 'loaded' of undefined
    at exit (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)

This is what i get, pls help
I am running Termux on an Android 8 Device

Node version: 13 (i cant get npm version since i can only get it with node)

**Comment by Throne3d** [comment]
I can't see any of this that's related to discord-irc. It looks like you're having a problem with [npm](https://github.com/npm/cli), which is not managed at this repository.
