### ISSUE TITLE
Can't Run (Missing environment variable CONFIG_FILE)

### ISSUE THREAD

**Issue by TLWXPUser** [reactiflux/discord-irc#526]
So, I'm using Termux which is a terminal for android with apps and that stuff, whenever i try to run a config file it will show up
```
/data/data/com.termux/files/usr/lib/node_modules/discord-irc/node_modules/check-env/index.js:12
      throw new Error('Missing environment variable ' + missing[0]);
      ^

Error: Missing environment variable CONFIG_FILE
    at module.exports (/data/data/com.termux/files/usr/lib/node_modules/discord-irc/node_modules/check-env/index.js:12:13)
    at Object.run [as default] (/data/data/com.termux/files/usr/lib/node_modules/discord-irc/dist/cli.js:396:27)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/discord-irc/dist/index.js:38:27)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11
```
I also have tried to run in a Windows 7 host, Same error.

I also have tried minimal configuration or close to example configuration, none worked.

**Comment by Throne3d** [comment]
You need to provide either a `CONFIG_FILE` environment variable, or a `--config` flag on the command line, pointing to a configuration file [like in the README](https://github.com/reactiflux/discord-irc#configuration). I usually see this error when that hasn't been provided, and the error message could be improved – did you do that?

**Comment by TLWXPUser** [comment]
No, i didnt, thanks for instructing me
