### ISSUE TITLE
ConfigurationError: The configuration file contains invalid JSON

### ISSUE THREAD

**Issue by UJIbU4** [reactiflux/discord-irc#566]
Can't launch discord-irc, output below:

C:\Users\rdp>discord-irc --config c:\discord\config.json
C:\Users\rdp\AppData\Roaming\npm\node_modules\discord-irc\dist\cli.js:40
      throw new _errors.ConfigurationError('The configuration file contains invalid JSON');
      ^

ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (C:\Users\rdp\AppData\Roaming\npm\node_modules\discord-irc\dist\cli.js:40:13)
    at Object.run [as default] (C:\Users\rdp\AppData\Roaming\npm\node_modules\discord-irc\dist\cli.js:56:98)
    at Object.<anonymous> (C:\Users\rdp\AppData\Roaming\npm\node_modules\discord-irc\dist\index.js:13:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

Config below:

[
  {
    "nickname": "test",
    "server": "irc.test.com",
    "discordToken": "token",
	"autoSendCommands": [
      ["PRIVMSG", "NickServ", "IDENTIFY", "password"]
],
    "channelMapping": {
      "1234566787876887789": "#channel"
    },
	"ircOptions": { 
      "floodProtection": false, 
      "floodProtectionDelay": 1000, 
      "port": "6697", 
      "secure": true, 
      "sasl": true, 
      "username": "test", 
      "password": "password" 
    },
	"format": { 
	"ircText": "!say <{$displayUsername}>: {$text}", 
	}
  }
]

**Comment by Throne3d** [comment]
Hi there! JSON doesn't allow trailing commas in objects, as in your `format` config after `ircText`'s definition.

Please use a JSON validator such as https://jsonlint.com/ to ensure your config file is valid. That should fix this problem!
