### ISSUE TITLE
Exit status 130

### ISSUE THREAD

**Issue by Miniontoby** [reactiflux/discord-irc#574]
`0 info it worked if it ends with ok

1 verbose cli [

1 verbose cli   'node',

1 verbose cli   '/usr/local/bin/npm',

1 verbose cli   'start',

1 verbose cli   '--',

1 verbose cli   '--config',

1 verbose cli   '/home/miniontoby/discord-irc/config2.json'

1 verbose cli ]

2 info using npm@6.13.4

3 info using node@v12.16.1

4 verbose node symlink /usr/local/bin/node

5 verbose run-script [ 'prestart', 'start', 'poststart' ]

6 info lifecycle discord-irc@2.8.1~prestart: discord-irc@2.8.1

7 info lifecycle discord-irc@2.8.1~start: discord-irc@2.8.1

8 verbose lifecycle discord-irc@2.8.1~start: unsafe-perm in lifecycle true

9 verbose lifecycle discord-irc@2.8.1~start: PATH: /usr/local/lib/node_modules/npm-lifecycle/node-gyp-bin:/home/miniontoby/discord-irc/node_modules/.bin:/usr/local/lib/nodejs/node-v10.15.0-linux-x64/bin:/home/miniontoby/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games

10 verbose lifecycle discord-irc@2.8.1~start: CWD: /home/miniontoby/discord-irc

11 silly lifecycle discord-irc@2.8.1~start: Args: [

11 silly lifecycle   '-c',

11 silly lifecycle   'node dist/index.js "--config" "/home/miniontoby/discord-irc/config2.json"'

11 silly lifecycle ]

12 silly lifecycle discord-irc@2.8.1~start: Returned: code: 130  signal: null

13 info lifecycle discord-irc@2.8.1~start: Failed to exec start script

14 verbose stack Error: discord-irc@2.8.1 start: 'node dist/index.js "--config" "/home/miniontoby/discord-irc/config2.json"'

14 verbose stack Exit status 130

14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm-lifecycle/index.js:332:16)

14 verbose stack     at EventEmitter.emit (events.js:311:20)

14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm-lifecycle/lib/spawn.js:55:14)

14 verbose stack     at ChildProcess.emit (events.js:311:20)

14 verbose stack     at maybeClose (internal/child_process.js:1021:16)

14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

15 verbose pkgid discord-irc@2.8.1

16 verbose cwd /home/miniontoby/discord-irc

17 verbose OpenBSD 6.8

18 verbose argv "node" "/usr/local/bin/npm" "start" "--" "--config" "/home/miniontoby/discord-irc/config2.json"

19 verbose node v12.16.1

20 verbose npm  v6.13.4

21 error code ELIFECYCLE

22 error errno 130

23 error discord-irc@2.8.1 start: 'node dist/index.js "--config" "/home/miniontoby/discord-irc/config2.json"'

23 error Exit status 130

24 error Failed at the discord-irc@2.8.1 start script.

24 error This is probably not a problem with npm. There is likely additional logging output above.

25 verbose exit [ 130, true ]
`
is my error, how to fix? It did worked before?

ps. in the real logs i can see it spams with
`
(node:37986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a c>

(node:37986) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.

    at RequestHandler.execute (/home/miniontoby/discord-irc/node_modules/discord.js/src/rest/RequestHandler.js:107:21)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

    at runNextTicks (internal/process/task_queues.js:66:3)

    at listOnTimeout (internal/timers.js:518:9)

    at processTimers (internal/timers.js:492:7)
`

**Comment by Throne3d** [comment]
Hi there! I actually have no idea what's up with an exit code 130 – I've not seen it before – but the logs complain about unsafe permissions and not being able to execute the start script. Maybe try reinstalling it?

Additionally, it looks like you're on 2.8.1 (outdated). Please upgrade to 2.9.0 and try again!

I've seen the `UnhandledPromiseRejectionWarning` error from time to time, and I think (as it did here) it typically comes from within `discord.js`. This was also updated in the 2.9.0 update, which may resolve the log spam.

Let me know how it goes
