### ISSUE TITLE
Bot error leads to crash.

### ISSUE THREAD

**Issue by Fudster** [reactiflux/discord-irc#620]
Can anyone look into this? 
`/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:31
        const message = channel._cacheMessage(new Message(channel, data, client));
                                ^

TypeError: channel._cacheMessage is not a function                               at MessageCreateAction.handle (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:31:33)
    at MessageCreateHandler.handle (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:8:51)    at WebSocketPacketManager.handle (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/receiver.js:422:14)```

**Comment by Fudster** [comment]
I found this https://github.com/nodejs/help/issues/3883

Hopefully that fixes it...we will see

**Comment by Katilmami** [comment]
solution of this error
npm uni discord.js
npm i discord.js-v11-stable
After that, Then
const Discord = require("discord.js");
delete this code and replace it with
const Discord = require("discord.js-v11-stable");
write your code And it's fixed, your problem is over
