### ISSUE TITLE
Sending any message in a voice channel text channel crashes this application

### ISSUE THREAD

**Issue by d223chen** [reactiflux/discord-irc#623]
Voice channels have accompanying text channels. It seems these do not have message caches, so sending a message in here crashes the discord.js module and thus the entire application. Would this be patchable here or does it need to be fixed in the discord.js module itself?

```
/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/local/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/local/lib/node_modules/discord-irc/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/discord-irc/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/discord-irc/node_modules/ws/lib/receiver.js:517:14)

**Comment by KeiroD** [comment]
Yep:

```
2023-02-20T05:28:58.866Z warn: Received warn event from Discord Discord sent a typing packet to a voice channel 848707213451067392
/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at module.exports [as MESSAGE_CREATE] (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/receiver.js:517:14)

Node.js v18.14.0
```

Looks like it's `discord.js` that's having the issue, so... probably update `discord.js`? I'll report back on this.

**Comment by KeiroD** [comment]
I've posted an upstream issue in `discord.js` [here](https://github.com/discordjs/discord.js/issues/9152) so hopefully this'll get fixed relatively quickly since it seems to be a `discord.js` issue.

**Comment by aronson** [comment]
I upgraded it to v14
https://github.com/reactiflux/discord-irc/pull/632
