### ISSUE TITLE
Messages not being sent to IRC

### ISSUE THREAD

**Issue by Awhile7127** [reactiflux/discord-irc#625]
Having an issue on startup:

```
info: Connected to IRC
error: Received error event from IRC Cannot read property 'trim' of undefined TypeError: Cannot read property 'trim' of undefined
    at Client.<anonymous> (/usr/local/lib/node_modules/discord-irc/node_modules/irc-upd/lib/irc.js:452:81)
    at Client.emit (events.js:198:13)
    at /usr/local/lib/node_modules/discord-irc/node_modules/irc-upd/lib/irc.js:896:26
    at Array.forEach (<anonymous>)
    at Socket.handleData (/usr/local/lib/node_modules/discord-irc/node_modules/irc-upd/lib/irc.js:890:15)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
info: Connected to Discord
```

Messages are being sent to Discord, but not to IRC. I don't think this is an issue with channel mapping or with bot permissions mentioned [here](https://github.com/reactiflux/discord-irc/issues/616), though unsure.

Anyone have a fix I'm missing?

**Comment by Awhile7127** [comment]
This project seems unmaintained.

Easier solution than debugging is to use something maintained, like [Matterbridge](https://github.com/42wim/matterbridge).

**Comment by Awhile7127** [comment]
This project seems unmaintained.

Easier solution than debugging is to use something maintained, like [Matterbridge](https://github.com/42wim/matterbridge).
