### ISSUE TITLE
Discord-irc crashes when unbanning in IRC

### ISSUE THREAD

**Issue by ZoeyCluff** [reactiflux/discord-irc#75]
I just cleared out my ban list on IRC, and it made the bridge crash. The bridge crashes with:

```
/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:845
                        throw err;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at chanModes (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:296:37)
    at /usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:315:25
    at Array.forEach (native)
    at Client.<anonymous> (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:266:26)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at iterator (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:842:26)
    at Array.forEach (native)
    at Socket.handleData (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:837:15)
    at emitOne (events.js:96:13)
```

it seems to be unable to parse the unban messages.

**Comment by ekmartin** [comment]
This looks to be the same issue as https://github.com/martynsmith/node-irc/issues/454. I'm gonna close this, since it's not something that can be handled in discord-irc (it needs to be fixed upstream, in node-irc). Thanks for the report though, and sorry for the extremely late answer!
