### ISSUE TITLE
Recurring Error During Very Busy Period

### ISSUE THREAD

**Issue by Samarian78** [reactiflux/discord-irc#91]
Hi guys,

Firstly thanks for making my life so much easier.  It's made our transition to Discord much smoother than I could have hoped for.
So we had a special event last night with unusually high usage for what we're used to (700+ active in Discord, 200+ active in IRC, average 140 messages per minute).  This particular error reocurred through the 12 hours.  Are you able to shed any light on it?

Regards,
Andy

TypeError: Cannot read property 'requestedDisconnect' of null
    at Client.send (/home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:932:19)
    at /home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:1072:22
    at Array.forEach (native)
    at /home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:1071:25
    at Array.forEach (native)
    at Client._speak (/home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:1069:12)
    at Client.say (/home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:1056:10)
    at /home/neonblue/Node/lib/node_modules/discord-irc/dist/bot.js:199:32
    at Bot.sendToIRC (/home/neonblue/Node/lib/node_modules/discord-irc/dist/bot.js:210:11)
    at Client.<anonymous> (/home/neonblue/Node/lib/node_modules/discord-irc/dist/bot.js:126:16)
/home/neonblue/Node/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:932
    if (!this.conn.requestedDisconnect) {

**Comment by ekmartin** [comment]
Hi @Samarian78. Sorry for the extremely late answer. discord-irc doesn't do much fancy stuff in terms of talking to discord, and relies heavily upon [discord.js](https://github.com/hydrabolt/discord.js) for that part. discord.js has recently gone through a complete refactor, and the latest version of discord-irc uses the newest version of that. Hopefully this should've been fixed, but feel free to let me know if it still persists and I'll reopen.
